export const 
    
        dzongkhag= [
          {
            name: "Chhukha",
            gewogs: [
              {
                name: "Bjacho",
                longitude: 27.079444,
                latitude: 89.585833,
              },
              {name:'Bongo',  latitude: 26.920278, longitude: 89.621944 },
               {name:'Chapcha', latitude: 27.193333, longitude: 89.537778 },
               {name:'Dala', latitude: 26.802778, longitude: 89.618056 },
               {name:'Dungna', latitude: 27.034722, longitude: 89.395278 },
               {name:'Geling', latitude: 27.015, longitude: 89.484167 },
                {name:'Getena', latitude: 26.935278, longitude: 89.737778 },
                   {name:'Metakha', latitude: 26.103333, longitude: 89.434722 },
                {name:'Logchina', latitude: 26.951389, longitude: 89.37 },
                {name:'Phuentsholing',
                      latitude: 26.883333,
                      longitude: 89.383333,
                    },
                    {name:'Sampheling', latitude: 26.838889, longitude: 89.491667 },
              
            ],
          },
          {
            name:'Haa',
            gewogs:[{name:'Bji',latitude: 27.474444, longitude: 89.191667 },
            {name:'Gakiling', latitude: 27.141667, longitude: 89.236389 },
            {name:'Katsho', latitude: 27.400833, longitude: 89.288333 },
            {name:'Samar',latitude: 27.298889, longitude: 89.253611 },
            {name:'Sangbay', latitude: 27.168889, longitude: 89.105278 },
                    {name:'Uesu',latitude: 27.340833, longitude: 89.314444 },
          ]},{
            name:'Dagana', gewogs: [
              
                  {name:'Dorona', latitude: 26.85, longitude: 89.833333 },
                  {name:'Drujegang', latitude: 26.95, longitude: 90.033333 },
                  {name:'Gesarling', latitude: 26.916667, longitude: 89.866667 },
                  {name:'Goshi', latitude: 26.916667, longitude: 89.95 },
                  {name:'Karna', latitude: 27, longitude: 89.829722 },
                  {name:'Karmaling', latitude: 26.766667, longitude: 89.95 },
                  {name:'Khebisa', latitude: 27.033333, longitude: 89.95 },
                  {name:'Lajab', latitude: 27.1, longitude: 90 },
                  {name:'LhamoyZingkha', latitude: 26.756944, longitude: 89.8 },
                  {name:'Nichula', latitude: 26.7625, longitude: 89.9625 },
                  {name:'Tashiding', latitude: 26.916667, longitude: 90 },
                  {name:'Tsangkha', latitude: 27.033333, longitude: 90.033333 },
                  {name:'Tsendagang', latitude: 26.875, longitude: 89.916667 },
                  {name:'Tseza', latitude: 27.150833, longitude: 89.829722 },
                
            ],},
            
            // Paro: {
            //   Doga: {},
            //   Dopshari: {},
            //   Doteng: {},
            //   Hungrel: {},
            //   Lamgong: {},
            //   Lungnyi: {},
            //   Naja: {},
            //   Shapa: {},
            //   Tsento: {},
            //   Wangchang: {},
            // },
            // Samtse: {
            //   Dungtoe: {},
            //   Dophoogchen: {},
            //   Duenchukha: {},
            //   Namgaychhoeling: {},
            //   Norbugang: {},
            //   Norgaygang: {},
            //   Pemaling: {},
            //   Phuentshogpelri: {},
            //   Samtse: {},
            //   Sangngagchhoeling: {},
            //   Tading: {},
            //   Tashicholing: {},
            //   Tendu: {},
            //   Ugentse: {},
            //   Yoeseltse: {},
            // },
            // Thimphu: {
            //   Chang: {},
            //   Dagala: {},
            //   Genyekha: {},
            //   Kawang: {},
            //   Lingzhi: {},
            //   Mewang: {},
            //   Naro: {},
            //   Soe: {},
            // },
            
            {name:'Gasa',gewogs: [
              
                  {name:'Goenkhamae', latitude: 27.75, longitude: 89.666667 },
                  {name:'Goenkaatoe', latitude: 27.833333, longitude: 89.633333 },
                  {name:'Laya', latitude: 28, longitude: 89.666667 },
                  {name:'Lunana', latitude: 28, longitude: 90.033333 },
              
            ]},
            // Punakha: {
            //   Barp: {},
            //   Chhubu: {},
            //   Dzomo: {},
            //   Goenshari: {},
            //   Guma: {},
            //   Kabjisa: {},
            //   Lingmukha: {},
            //   ShengaBjime: {},
            //   Talog: {},
            //   Toepisa: {},
            //   Towang: {},
            // },
            // Tsirang: {
            //   Barshong: {},
            //   Dunglegang: {},
            //   Goseling: {},
            //   Kikhorthang: {},
            //   Mendrelgang: {},
            //   Patshaling: {},
            //   Phutenchhu: {},
            //   Rangthangling: {},
            //   Semjong: {},
            //   Sergithang: {},
            //   Tsholingkhar: {},
            //   Tsirangtoe: {},
            // },
            // WangduePhodrang: {
            //   Athang: {},
            //   Bjena: {},
            //   Daga: {},
            //   Dangchu: {},
            //   Gangte: {},
            //   GasetshoGom: {},
            //   GasetshoOm: {},
            //   Kazhi: {},
            //   Nahi: {},
            //   Nyisho: {},
            //   Phangyuel: {},
            //   Phobji: {},
            //   Ruepisa: {},
            //   Sephu: {},
            //   Thedtsho: {},
            // },
           { name:'Bumthang',gewogs: [
                  {name:'Chhoekhor', latitude: 27.559167, longitude: 90.733333 },
                  {name:'Chhume',latitude: 27.494444, longitude: 90.666667 },
                  {name:'Tang', latitude: 27.558056, longitude: 90.804444 },
                  {name:'Ura', latitude: 27.466667, longitude: 90.9 },
            ]},
            // Sarpang: {
            //   Chhuzagang: {},
            //   Chhudzom: {},
            //   Dekiling: {},
            //   Gakiling: {},
            //   Gelephu: {},
            //   Jigmechhoeling: {},
            //   Samtenling: {},
            //   Senghe: {},
            //   Serzhong: {},
            //   Shompangkha: {},
            //   Tareythang: {},
            //   Umling: {},
            // },
            // Trongsa: {
            //   Dragteng: {},
            //   Korphu: {},
            //   Langthil: {},
            //   Nubi: {},
            //   Tangsibji: {},
            // },
            // Zhemgang: {
            //   Bardho: {},
            //   Bjoka: {},
            //   Goshing: {},
            //   Nangkor: {},
            //   Ngangla: {},
            //   Phangkhar: {},
            //   Shingkhar: {},
            //   Trong: {},
            // },
            // Lhuntse: {
            //   Gangzur: {},
            //   Jaray: {},
            //   Khoma: {},
            //   Kurtoe: {},
            //   Menbi: {},
            //   Metsho: {},
            //   Minjay: {},
            //   Tsenkhar: {},
            // },
            // Mongar: {
            //   Balam: {},
            //   Chaskhar: {},
            //   Chhali: {},
            //   Drametse: {},
            //   Drepung: {},
            //   Gongdue: {},
            //   Jurmey: {},
            //   Kengkhar: {},
            //   Mongar: {},
            //   Narang: {},
            //   Ngatshang: {},
            //   Saleng: {},
            //   Sherimung: {},
            //   Silambi: {},
            //   Thangrong: {},
            //   Tsakaling: {},
            //   Tsamang: {},
            // },
            // PemaGatshel: {
            //   Chhimung: {},
            //   Choekhorling: {},
            //   ChongshingBorang: {},
            //   Dechenling: {},
            //   Dungme: {},
            //   Khar: {},
            //   Nanong: {},
            //   Norbugang: {},
            //   Shumar: {},
            //   Yurung: {},
            //   Zobel: {},
            // },
            // SamdrupJongkhar: {
            //   Dewathang: {},
            //   Gomdar: {},
            //   Langchenphu: {},
            //   Lauri: {},
            //   Martshala: {},
            //   Orong: {},
            //   Pemathang: {},
            //   Phuntshothang: {},
            //   Samrang: {},
            //   Serthi: {},
            //   Wangphu: {},
            // },
            // Trashigang: {
            //   Bartsham: {},
            //   Bidung: {},
            //   Kanglung: {},
            //   Kangpara: {},
            //   Khaling: {},
            //   Lumang: {},
            //   Merak: {},
            //   Phongmey: {},
            //   Radhi: {},
            //   Sakteng: {},
            //   Samkhar: {},
            //   Shongphu: {},
            //   Thrimshing: {},
            //   Uzorong: {},
            //   Yangneer: {},
            // },
            // TrashiYangtse: {
            //   Bumdeling: {},
            //   Jamkhar: {},
            //   Khamdang: {},
            //   Ramjar: {},
            //   Toetsho: {},
            //   Tomzhangtshen: {},
            //   Trashiyangtse: {},
            //   Yalang: {},
            // },
          
        ]
      